### ISSUE TITLE
Błąd kompilacji

### ISSUE THREAD

**Issue by Atex0r-r** [mako777/RenaultAffa2#1]
Witam . Przy próbie kombilacji programu z pliku main, wywala o to te błędy.
Więc ostatecznie nic nie da się skompilować, nawet goły program z komendą write_text_sagem wyrzuca błąd kompilacji.
`Arduino:1.8.10 (Windows 10), Płytka:"Arduino Nano, ATmega328P (Old Bootloader)"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\barte\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\barte\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\barte\Documents\Arduino\libraries -fqbn=arduino:avr:nano:cpu=atmega328old -vid-pid=1A86_7523 -ide-version=10810 -build-path C:\Users\barte\AppData\Local\Temp\arduino_build_462413 -warnings=none -build-cache C:\Users\barte\AppData\Local\Temp\arduino_cache_655678 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Users\barte\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino5.path=C:\Users\barte\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5 -prefs=runtime.tools.arduinoOTA.path=C:\Users\barte\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=C:\Users\barte\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0 -prefs=runtime.tools.avrdude.path=C:\Users\barte\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17 -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=C:\Users\barte\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17 -verbose C:\Users\barte\Documents\Arduino\sketch_dec26afff\sketch_dec26afff.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\barte\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\barte\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\barte\Documents\Arduino\libraries -fqbn=arduino:avr:nano:cpu=atmega328old -vid-pid=1A86_7523 -ide-version=10810 -build-path C:\Users\barte\AppData\Local\Temp\arduino_build_462413 -warnings=none -build-cache C:\Users\barte\AppData\Local\Temp\arduino_cache_655678 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=C:\Users\barte\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino5.path=C:\Users\barte\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino5 -prefs=runtime.tools.arduinoOTA.path=C:\Users\barte\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=C:\Users\barte\AppData\Local\Arduino15\packages\arduino\tools\arduinoOTA\1.3.0 -prefs=runtime.tools.avrdude.path=C:\Users\barte\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17 -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=C:\Users\barte\AppData\Local\Arduino15\packages\arduino\tools\avrdude\6.3.0-arduino17 -verbose C:\Users\barte\Documents\Arduino\sketch_dec26afff\sketch_dec26afff.ino
Using board 'nano' from platform in folder: C:\Program
Using core 'arduino' from platform in folder: C:\Program
Detecting libraries used...
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\sketch\\sketch_dec26afff.ino.cpp" -o nul
Alternatives for I2cbase.h: [RenaultAffa2-master]
ResolveLibrary(I2cbase.h)
  -> candidates: [RenaultAffa2-master]
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\sketch\\sketch_dec26afff.ino.cpp" -o nul
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master\\I2CBase.cpp" -o nul
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master\\main.cpp" -o nul
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master\\sagem_affa2.cpp" -o nul
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master\\timer.c" -o nul
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master\\usart.c" -o nul
Generating function prototypes...
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\sketch\\sketch_dec26afff.ino.cpp" -o "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\preproc\\ctags_target_for_gcc_minus_e.cpp"
"C:\\Program Files (x86)\\Arduino\\tools-builder\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\preproc\\ctags_target_for_gcc_minus_e.cpp"
Kompilowanie szkicu...
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\sketch\\sketch_dec26afff.ino.cpp" -o "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\sketch\\sketch_dec26afff.ino.cpp.o"
Compiling libraries...
Compiling library "RenaultAffa2-master"
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-gcc" -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master\\usart.c" -o "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\libraries\\RenaultAffa2-master\\usart.c.o"
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-gcc" -c -g -Os -w -std=gnu11 -ffunction-sections -fdata-sections -MMD -flto -fno-fat-lto-objects -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master\\timer.c" -o "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\libraries\\RenaultAffa2-master\\timer.c.o"
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master\\main.cpp" -o "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\libraries\\RenaultAffa2-master\\main.cpp.o"
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master\\sagem_affa2.cpp" -o "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\libraries\\RenaultAffa2-master\\sagem_affa2.cpp.o"
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_NANO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\eightanaloginputs" "-IC:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master" "C:\\Users\\barte\\Documents\\Arduino\\libraries\\RenaultAffa2-master\\I2CBase.cpp" -o "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\libraries\\RenaultAffa2-master\\I2CBase.cpp.o"
Compiling core...
Using precompiled core: C:\Users\barte\AppData\Local\Temp\arduino_cache_655678\core\core_arduino_avr_nano_cpu_atmega328old_0c812875ac70eb4a9b385d8fb077f54c.a
Linking everything together...
"C:\\Users\\barte\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\7.3.0-atmel3.6.1-arduino5/bin/avr-gcc" -w -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections -mmcu=atmega328p -o "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413/sketch_dec26afff.ino.elf" "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\sketch\\sketch_dec26afff.ino.cpp.o" "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\libraries\\RenaultAffa2-master\\timer.c.o" "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\libraries\\RenaultAffa2-master\\usart.c.o" "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\libraries\\RenaultAffa2-master\\I2CBase.cpp.o" "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\libraries\\RenaultAffa2-master\\main.cpp.o" "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413\\libraries\\RenaultAffa2-master\\sagem_affa2.cpp.o" "C:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413/..\\arduino_cache_655678\\core\\core_arduino_avr_nano_cpu_atmega328old_0c812875ac70eb4a9b385d8fb077f54c.a" "-LC:\\Users\\barte\\AppData\\Local\\Temp\\arduino_build_462413" -lm
C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `r2rReset(timeoutarg)'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `resetPending'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `displayReset'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `__vector_16'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `timer1ms'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `timer1s'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `displayText(char const*)'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `welcomeScreen(timeoutarg)'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `displayVoltage(timeoutarg)'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `refreshDisplay'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `voltage'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `r2rSet(unsigned char)'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `measureVoltage(int)'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `main'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\libraries\RenaultAffa2-master\main.cpp.o (symbol from plugin): In function `r2rReset(timeoutarg)':

(.text+0x0): multiple definition of `displayWatchdog'

C:\Users\barte\AppData\Local\Temp\arduino_build_462413\sketch\sketch_dec26afff.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

C:\Users\barte\AppData\Local\Temp\ccsrl3FA.ltrans0.ltrans.o: In function `uart0_putc':

C:\Users\barte\Documents\Arduino\libraries\RenaultAffa2-master/usart.c:419: undefined reference to `tx0_buffer'

C:\Users\barte\Documents\Arduino\libraries\RenaultAffa2-master/usart.c:419: undefined reference to `tx0_buffer'

C:\Users\barte\AppData\Local\Temp\ccsrl3FA.ltrans0.ltrans.o: In function `uart_getchar':

C:\Users\barte\Documents\Arduino\libraries\RenaultAffa2-master/usart.c:3044: undefined reference to `rx0_buffer'

C:\Users\barte\Documents\Arduino\libraries\RenaultAffa2-master/usart.c:3044: undefined reference to `rx0_buffer'

C:\Users\barte\AppData\Local\Temp\ccsrl3FA.ltrans0.ltrans.o: In function `__vector_18':

C:\Users\barte\Documents\Arduino\libraries\RenaultAffa2-master/usart.c:4875: undefined reference to `rx0_buffer'

C:\Users\barte\Documents\Arduino\libraries\RenaultAffa2-master/usart.c:4875: undefined reference to `rx0_buffer'

C:\Users\barte\AppData\Local\Temp\ccsrl3FA.ltrans0.ltrans.o: In function `__vector_19':

Znaleziono wiele bibliotek w "I2cbase.h"
Wykorzystane: C:\Users\barte\Documents\Arduino\libraries\RenaultAffa2-master
C:\Users\barte\Documents\Arduino\libraries\RenaultAffa2-master/usart.c:4704: undefined reference to `tx0_buffer'

C:\Users\barte\Documents\Arduino\libraries\RenaultAffa2-master/usart.c:4704: undefined reference to `tx0_buffer'

C:\Users\barte\AppData\Local\Temp\ccsrl3FA.ltrans0.ltrans.o: In function `main':

C:\Users\barte\Documents\Arduino\sketch_dec26afff/sketch_dec26afff.ino:171: undefined reference to `initA2D(unsigned char)'

C:\Users\barte\AppData\Local\Temp\ccsrl3FA.ltrans0.ltrans.o: In function `uart0_getln':

C:\Users\barte\Documents\Arduino\libraries\RenaultAffa2-master/usart.c:2787: undefined reference to `uart0_getc'

C:\Users\barte\Documents\Arduino\libraries\RenaultAffa2-master/usart.c:2787: undefined reference to `uart0_getc'

C:\Users\barte\AppData\Local\Temp\ccsrl3FA.ltrans0.ltrans.o: In function `measureVoltage':

C:\Users\barte\Documents\Arduino\sketch_dec26afff/sketch_dec26afff.ino:119: undefined reference to `readA2D(signed char)'

collect2.exe: error: ld returned 1 exit status

Użycie biblioteki RenaultAffa2-master z folderu C:\Users\barte\Documents\Arduino\libraries\RenaultAffa2-master (legacy)
exit status 1
Błąd kompilacji dla płytki Arduino Nano.`

**Comment by mako777** [comment]
Witam,
Z tego co widzę próbujesz skompilować to w środowisku Arduino, a to nie jest napisane w Arduino tylko w normalnym C++, więc nic dziwnego że nie daje się skompilować. Arduino jest tu wykorzystane tylko jako łatwy w użyciu "hardware".

**Comment by mako777** [comment]
Dla każdego kto nie chce się bawić w kompilacje kodu, wrzuciłem do zakładki "release" skompilowany program, tylko wgrać na płytkę arduino nano i można używać (oczywiście układ musi być zmontowany wedle schematu który zamieściłem).
