### ISSUE TITLE
Ciekawe czy skrula działa?

### ISSUE THREAD

**Issue by LubomirVt** [mako777/RenaultAffa2#2]
Witam, 
Ciekawe czy skrula działa?
Które przyciski zakrywa?

**Comment by mako777** [comment]
Witam,
Nie do końca rozumiem co tu jest napisane. 

Write in english maybe ?

**Comment by LubomirVt** [comment]
Hello,
Does the scroll on the back of the remote work?

These files are not available in your project, but are included in the source:
#include <avr/io.h>
#include <avr/interrupt.h>
#include <avr/eeprom.h>
#include <util/delay.h>
#include <avr/wdt.h>

Best regards.

**Comment by mako777** [comment]
Yes, the scroll works, it is coded as next/prev.

These files are standard includes, they come with the compiler.
If You have problem with compiling source code I have included compiled "hex" file in the "release" segment, You only has to upload it to the arduino nano board and You are good to go.

**Comment by LubomirVt** [comment]
I found out about the hex file. I want if he needs to change a caption or something else.
